# Text Preprocessing
Disclosure: pode haver erros nas tarefas de pré-processamento. O objetivo deste notebook é treinar a parte código de python aplicado a NLP.

## a) With pandas

### 0 - Creating datasets

In [1]:
import pandas as pd

In [2]:
data_pt = [
    "Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.",
    "Se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.",
    "Fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.",
    "O miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.",
    "Estou a pensar seriamente em tirar uns dias de férias no Algarve para aproveitar o calor e a praia.",
    "Deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?",
    "Ontem fomos jantar fora e comemos um bacalhau à Brás que estava simplesmente divinal.",
    "Corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.",
    "Fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.",
    "Amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.",
]

data_en = [
    "I love to read interesting books in the evening before going to sleep.",
    "The sun is shining brightly today, so we should go to the park.",
    "She works as a manager at a large international bank in Lisbon.",
    "We usually eat a delicious dinner together at seven o'clock.",
    "He lives in a big city because he likes the busy lifestyle.",
    "They play soccer with their friends every weekend at the local field.",
    "My dog always barks loudly whenever the mailman arrives at the door.",
    "The coffee is still very hot, so you should wait a few minutes.",
    "I want to learn English to get a better job in the future.",
    "Drinking enough water every day is extremely important for your health.",
]

In [3]:
data_pt

['Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.',
 'Se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.',
 'Fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.',
 'O miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.',
 'Estou a pensar seriamente em tirar uns dias de férias no Algarve para aproveitar o calor e a praia.',
 'Deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?',
 'Ontem fomos jantar fora e comemos um bacalhau à Brás que estava simplesmente divinal.',
 'Corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.',
 'Fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.',
 'Amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.']

In [4]:
data_en

['I love to read interesting books in the evening before going to sleep.',
 'The sun is shining brightly today, so we should go to the park.',
 'She works as a manager at a large international bank in Lisbon.',
 "We usually eat a delicious dinner together at seven o'clock.",
 'He lives in a big city because he likes the busy lifestyle.',
 'They play soccer with their friends every weekend at the local field.',
 'My dog always barks loudly whenever the mailman arrives at the door.',
 'The coffee is still very hot, so you should wait a few minutes.',
 'I want to learn English to get a better job in the future.',
 'Drinking enough water every day is extremely important for your health.']

In [5]:
# setting the width of the column to the maximum for the dataframe:
pd.set_option('display.max_colwidth', None)

In [6]:
data_pt_df = pd.DataFrame(data_pt, columns=['frases'])
data_pt_df

                                                                                                        frases
0            Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.
1     Se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.
2            Fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.
3   O miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.
4          Estou a pensar seriamente em tirar uns dias de férias no Algarve para aproveitar o calor e a praia.
5                          Deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?
6                        Ontem fomos jantar fora e comemos um bacalhau à Brás que estava simplesmente divinal.
7               Corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.
8  Fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.
9                      Amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.

In [7]:
data_en_df = pd.DataFrame(data_en, columns=['frases'])
data_en_df

                                                                    frases
0   I love to read interesting books in the evening before going to sleep.
1          The sun is shining brightly today, so we should go to the park.
2          She works as a manager at a large international bank in Lisbon.
3             We usually eat a delicious dinner together at seven o'clock.
4              He lives in a big city because he likes the busy lifestyle.
5    They play soccer with their friends every weekend at the local field.
6     My dog always barks loudly whenever the mailman arrives at the door.
7          The coffee is still very hot, so you should wait a few minutes.
8               I want to learn English to get a better job in the future.
9  Drinking enough water every day is extremely important for your health.

### 1 - Text preprocessing
Nota: é sempre melhor fazer uma cópia de cada dataframe (i.e., os dados originais) para não se perder ou dar *overwrite* sem querer.

#### Fazer cópias das dataframes *data_pt_df*


*   data_pt_df -> variável "df_pt"
*   data_en_df -> variável "df_en"

In [8]:
df_pt = data_pt_df.copy()
df_pt

                                                                                                        frases
0            Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.
1     Se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.
2            Fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.
3   O miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.
4          Estou a pensar seriamente em tirar uns dias de férias no Algarve para aproveitar o calor e a praia.
5                          Deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?
6                        Ontem fomos jantar fora e comemos um bacalhau à Brás que estava simplesmente divinal.
7               Corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.
8  Fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.
9                      Amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.

In [9]:
df_en = data_en_df.copy()
df_en

                                                                    frases
0   I love to read interesting books in the evening before going to sleep.
1          The sun is shining brightly today, so we should go to the park.
2          She works as a manager at a large international bank in Lisbon.
3             We usually eat a delicious dinner together at seven o'clock.
4              He lives in a big city because he likes the busy lifestyle.
5    They play soccer with their friends every weekend at the local field.
6     My dog always barks loudly whenever the mailman arrives at the door.
7          The coffee is still very hot, so you should wait a few minutes.
8               I want to learn English to get a better job in the future.
9  Drinking enough water every day is extremely important for your health.

#### *Lowercasing*
O ato de colocar todas as palavras em minúsculas (lowercase).

In [10]:
df_pt['lowercase'] = df_pt['frases'].str.lower()
df_pt

,frases,lowercase
0,Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.,vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.
1,"Se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.","se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho."
2,"Fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.","fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio."
3,O miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.,o miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.
4,Estou a pensar seriamente em tirar uns dias de férias no Algarve para aproveitar o calor e a praia.,estou a pensar seriamente em tirar uns dias de férias no algarve para aproveitar o calor e a praia.
5,"Deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?","deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?"
6,Ontem fomos jantar fora e comemos um bacalhau à Brás que estava simplesmente divinal.,ontem fomos jantar fora e comemos um bacalhau à brás que estava simplesmente divinal.
7,"Corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.","corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro."
8,"Fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.","fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo."
9,Amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.,amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.

In [11]:
df_en['lowercase'] = df_en['frases'].str.lower()
df_en

,frases,lowercase
0,I love to read interesting books in the evening before going to sleep.,i love to read interesting books in the evening before going to sleep.
1,"The sun is shining brightly today, so we should go to the park.","the sun is shining brightly today, so we should go to the park."
2,She works as a manager at a large international bank in Lisbon.,she works as a manager at a large international bank in lisbon.
3,We usually eat a delicious dinner together at seven o'clock.,we usually eat a delicious dinner together at seven o'clock.
4,He lives in a big city because he likes the busy lifestyle.,he lives in a big city because he likes the busy lifestyle.
5,They play soccer with their friends every weekend at the local field.,they play soccer with their friends every weekend at the local field.
6,My dog always barks loudly whenever the mailman arrives at the door.,my dog always barks loudly whenever the mailman arrives at the door.
7,"The coffee is still very hot, so you should wait a few minutes.","the coffee is still very hot, so you should wait a few minutes."
8,I want to learn English to get a better job in the future.,i want to learn english to get a better job in the future.
9,Drinking enough water every day is extremely important for your health.,drinking enough water every day is extremely important for your health.

#### Remover pontuação e símbolos especiais
Nota: isto vai remover todo o tipo de pontuação e outros símbolos que não sejam caracteres de letras ou de espaço em branco. Isto pode ter efeitos diferentes dependendo do tipo de caracteres que cada língua usa. Por exemplo, o inglês utiliza o símbolo **'** para expressar diferentes significados e relações entre palavras.

In [12]:
df_pt['remove_ponctuation'] = df_pt['lowercase'].str.replace(r'[^\w\s]', '', regex=True)
df_pt

,frases,lowercase,remove_ponctuation
0,Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.,vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.,vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover
1,"Se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.","se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.",se fores ao supermercado traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho
2,"Fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.","fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.",fiquei imenso tempo na paragem à espera do autocarro mas ele acabou por vir completamente cheio
3,O miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.,o miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.,o miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa
4,Estou a pensar seriamente em tirar uns dias de férias no Algarve para aproveitar o calor e a praia.,estou a pensar seriamente em tirar uns dias de férias no algarve para aproveitar o calor e a praia.,estou a pensar seriamente em tirar uns dias de férias no algarve para aproveitar o calor e a praia
5,"Deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?","deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?",deixei as chaves de casa em cima da cómoda do quarto podes ir buscálas por favor
6,Ontem fomos jantar fora e comemos um bacalhau à Brás que estava simplesmente divinal.,ontem fomos jantar fora e comemos um bacalhau à brás que estava simplesmente divinal.,ontem fomos jantar fora e comemos um bacalhau à brás que estava simplesmente divinal
7,"Corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.","corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.",corta mas é o cabelo que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro
8,"Fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.","fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.",fiquei farto de estar na fila das finanças aquilo estava uma confusão pegada e o sistema ainda foi abaixo
9,Amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.,amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.,amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana

In [13]:
df_en['remove_ponctuation'] = df_en['lowercase'].str.replace(r'[^\w\s]', '', regex=True)
df_en

,frases,lowercase,remove_ponctuation
0,I love to read interesting books in the evening before going to sleep.,i love to read interesting books in the evening before going to sleep.,i love to read interesting books in the evening before going to sleep
1,"The sun is shining brightly today, so we should go to the park.","the sun is shining brightly today, so we should go to the park.",the sun is shining brightly today so we should go to the park
2,She works as a manager at a large international bank in Lisbon.,she works as a manager at a large international bank in lisbon.,she works as a manager at a large international bank in lisbon
3,We usually eat a delicious dinner together at seven o'clock.,we usually eat a delicious dinner together at seven o'clock.,we usually eat a delicious dinner together at seven oclock
4,He lives in a big city because he likes the busy lifestyle.,he lives in a big city because he likes the busy lifestyle.,he lives in a big city because he likes the busy lifestyle
5,They play soccer with their friends every weekend at the local field.,they play soccer with their friends every weekend at the local field.,they play soccer with their friends every weekend at the local field
6,My dog always barks loudly whenever the mailman arrives at the door.,my dog always barks loudly whenever the mailman arrives at the door.,my dog always barks loudly whenever the mailman arrives at the door
7,"The coffee is still very hot, so you should wait a few minutes.","the coffee is still very hot, so you should wait a few minutes.",the coffee is still very hot so you should wait a few minutes
8,I want to learn English to get a better job in the future.,i want to learn english to get a better job in the future.,i want to learn english to get a better job in the future
9,Drinking enough water every day is extremely important for your health.,drinking enough water every day is extremely important for your health.,drinking enough water every day is extremely important for your health

## b) With spaCy

In [14]:
import spacy
!python -m spacy download pt_core_news_sm

Collecting pt-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 57.1 MB/s eta 0:00:00
Installing collected packages: pt-core-news-sm
Successfully installed pt-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

É preciso fazer load dos modelos pré-treinados do spaCy em todas as línguas que estão a ser pré-processadas:

In [15]:
english = spacy.load('en_core_web_sm')
portuguese = spacy.load('pt_core_news_sm')

#### Tokenização

In [16]:
df_pt['tokens'] = df_pt['frases'].apply(portuguese)
df_pt

,frases,lowercase,remove_ponctuation,tokens
0,Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.,vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.,vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover,"(Vou, só, ali, ao, café, da, esquina, pedir, uma, bica, e, comer, um, pastel, de, nata, antes, que, comece, a, chover, .)"
1,"Se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.","se fores ao supermercado, traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho.",se fores ao supermercado traz um pacote de miolo de noz e não te esqueças de meter a moeda no carrinho,"(Se, fores, ao, supermercado, ,, traz, um, pacote, de, miolo, de, noz, e, não, te, esqueças, de, meter, a, moeda, no, carrinho, .)"
2,"Fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.","fiquei imenso tempo na paragem à espera do autocarro, mas ele acabou por vir completamente cheio.",fiquei imenso tempo na paragem à espera do autocarro mas ele acabou por vir completamente cheio,"(Fiquei, imenso, tempo, na, paragem, à, espera, do, autocarro, ,, mas, ele, acabou, por, vir, completamente, cheio, .)"
3,O miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.,o miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa.,o miúdo mais novo passou o fim de semana todo a jogar consola e agora não quer fazer os trabalhos de casa,"(O, miúdo, mais, novo, passou, o, fim, de, semana, todo, a, jogar, consola, e, agora, não, quer, fazer, os, trabalhos, de, casa, .)"
4,Estou a pensar seriamente em tirar uns dias de férias no Algarve para aproveitar o calor e a praia.,estou a pensar seriamente em tirar uns dias de férias no algarve para aproveitar o calor e a praia.,estou a pensar seriamente em tirar uns dias de férias no algarve para aproveitar o calor e a praia,"(Estou, a, pensar, seriamente, em, tirar, uns, dias, de, férias, no, Algarve, para, aproveitar, o, calor, e, a, praia, .)"
5,"Deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?","deixei as chaves de casa em cima da cómoda do quarto, podes ir buscá-las por favor?",deixei as chaves de casa em cima da cómoda do quarto podes ir buscálas por favor,"(Deixei, as, chaves, de, casa, em, cima, da, cómoda, do, quarto, ,, podes, ir, buscá-las, por, favor, ?)"
6,Ontem fomos jantar fora e comemos um bacalhau à Brás que estava simplesmente divinal.,ontem fomos jantar fora e comemos um bacalhau à brás que estava simplesmente divinal.,ontem fomos jantar fora e comemos um bacalhau à brás que estava simplesmente divinal,"(Ontem, fomos, jantar, fora, e, comemos, um, bacalhau, à, Brás, que, estava, simplesmente, divinal, .)"
7,"Corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.","corta mas é o cabelo, que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro.",corta mas é o cabelo que já estás com um ar muito desalinhado e a precisar de ir ao barbeiro,"(Corta, mas, é, o, cabelo, ,, que, já, estás, com, um, ar, muito, desalinhado, e, a, precisar, de, ir, ao, barbeiro, .)"
8,"Fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.","fiquei farto de estar na fila das finanças, aquilo estava uma confusão pegada e o sistema ainda foi abaixo.",fiquei farto de estar na fila das finanças aquilo estava uma confusão pegada e o sistema ainda foi abaixo,"(Fiquei, farto, de, estar, na, fila, das, finanças, ,, aquilo, estava, uma, confusão, pegada, e, o, sistema, ainda, foi, abaixo, .)"
9,Amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.,amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana.,amanhã de manhã tenho de ir correr cedinho para compensar os excessos do fim de semana,"(Amanhã, de, manhã, tenho, de, ir, correr, cedinho, para, compensar, os, excessos, do, fim, de, semana, .)"

In [17]:
df_en['tokens'] = df_en['frases'].apply(english)
df_en

,frases,lowercase,remove_ponctuation,tokens
0,I love to read interesting books in the evening before going to sleep.,i love to read interesting books in the evening before going to sleep.,i love to read interesting books in the evening before going to sleep,"(I, love, to, read, interesting, books, in, the, evening, before, going, to, sleep, .)"
1,"The sun is shining brightly today, so we should go to the park.","the sun is shining brightly today, so we should go to the park.",the sun is shining brightly today so we should go to the park,"(The, sun, is, shining, brightly, today, ,, so, we, should, go, to, the, park, .)"
2,She works as a manager at a large international bank in Lisbon.,she works as a manager at a large international bank in lisbon.,she works as a manager at a large international bank in lisbon,"(She, works, as, a, manager, at, a, large, international, bank, in, Lisbon, .)"
3,We usually eat a delicious dinner together at seven o'clock.,we usually eat a delicious dinner together at seven o'clock.,we usually eat a delicious dinner together at seven oclock,"(We, usually, eat, a, delicious, dinner, together, at, seven, o'clock, .)"
4,He lives in a big city because he likes the busy lifestyle.,he lives in a big city because he likes the busy lifestyle.,he lives in a big city because he likes the busy lifestyle,"(He, lives, in, a, big, city, because, he, likes, the, busy, lifestyle, .)"
5,They play soccer with their friends every weekend at the local field.,they play soccer with their friends every weekend at the local field.,they play soccer with their friends every weekend at the local field,"(They, play, soccer, with, their, friends, every, weekend, at, the, local, field, .)"
6,My dog always barks loudly whenever the mailman arrives at the door.,my dog always barks loudly whenever the mailman arrives at the door.,my dog always barks loudly whenever the mailman arrives at the door,"(My, dog, always, barks, loudly, whenever, the, mailman, arrives, at, the, door, .)"
7,"The coffee is still very hot, so you should wait a few minutes.","the coffee is still very hot, so you should wait a few minutes.",the coffee is still very hot so you should wait a few minutes,"(The, coffee, is, still, very, hot, ,, so, you, should, wait, a, few, minutes, .)"
8,I want to learn English to get a better job in the future.,i want to learn english to get a better job in the future.,i want to learn english to get a better job in the future,"(I, want, to, learn, English, to, get, a, better, job, in, the, future, .)"
9,Drinking enough water every day is extremely important for your health.,drinking enough water every day is extremely important for your health.,drinking enough water every day is extremely important for your health,"(Drinking, enough, water, every, day, is, extremely, important, for, your, health, .)"

#### Stop Words
Stop Words são palavras  que não adicionam significado semântico relevante para o entendimento do sistema sobre determinado texto.
É preciso dar load também da lista das stops words, uma para cada modelo de língua, uma variável para cada.

In [18]:
stopwords_pt = portuguese.Defaults.stop_words
stopwords_en = english.Defaults.stop_words

O spaCy só consegue tirar as stop words com uma string. Assim, é preciso alterar a dataframe para strings. Por agora, usa-se apenas uma das frases para cada língua:

In [19]:
str_pt = df_pt['frases'].iloc[0]
str_pt

'Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.'

In [20]:
str_en = df_en['frases'].iloc[0]
str_en

'I love to read interesting books in the evening before going to sleep.'

Depois de estar no tipo de dados correto, colocar cada frase numa variável (para cada língua):

In [21]:
doc_pt = portuguese(str_pt)
doc_pt

Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.

In [22]:
doc_en = english(str_en)
doc_en

I love to read interesting books in the evening before going to sleep.

Agora é só fazer a remoção de stop words:

In [23]:
[token.text for token in doc_pt if not token.is_stop]

['Vou',
 'café',
 'esquina',
 'pedir',
 'bica',
 'comer',
 'pastel',
 'nata',
 'comece',
 'chover',
 '.']

In [24]:
[token.text for token in doc_en if not token.is_stop]

['love', 'read', 'interesting', 'books', 'evening', 'going', 'sleep', '.']

#### Lematização
Pode ser feito de forma similar à remoção de stop words:

In [25]:
[token.lemma_ for token in doc_pt]

['Vou',
 'só',
 'ali',
 'a o',
 'café',
 'de o',
 'esquina',
 'pedir',
 'um',
 'bica',
 'e',
 'comer',
 'um',
 'pastel',
 'de',
 'nata',
 'antes',
 'que',
 'começar',
 'a',
 'chover',
 '.']

In [26]:
[token.lemma_ for token in doc_en]

['I',
 'love',
 'to',
 'read',
 'interesting',
 'book',
 'in',
 'the',
 'evening',
 'before',
 'go',
 'to',
 'sleep',
 '.']

#### Parts-Of-Speech (POS) tagging
Para isto, é preciso utilizar outro conjunto de frases, visto que o objetivo é dar uma etiqueta (tag) a todas as palavras da frase e não apenas às que são relevantes para o sistema.

Atenção: Cuidado com a sobreposição de variáveis!

In [27]:
doc_pt2 = portuguese(str_pt)
doc_pt2

Vou só ali ao café da esquina pedir uma bica e comer um pastel de nata antes que comece a chover.

In [28]:
doc_en2 = english(str_en)
doc_en2

I love to read interesting books in the evening before going to sleep.

Agora procedemos ao POS tagging:

In [29]:
[(token.text, token.pos_ ) for token in doc_pt2]

[('Vou', 'AUX'),
 ('só', 'ADV'),
 ('ali', 'ADV'),
 ('ao', 'ADP'),
 ('café', 'NOUN'),
 ('da', 'ADP'),
 ('esquina', 'NOUN'),
 ('pedir', 'VERB'),
 ('uma', 'DET'),
 ('bica', 'NOUN'),
 ('e', 'CCONJ'),
 ('comer', 'VERB'),
 ('um', 'DET'),
 ('pastel', 'NOUN'),
 ('de', 'ADP'),
 ('nata', 'NOUN'),
 ('antes', 'ADV'),
 ('que', 'SCONJ'),
 ('comece', 'VERB'),
 ('a', 'SCONJ'),
 ('chover', 'VERB'),
 ('.', 'PUNCT')]

In [30]:
[(token.text, token.pos_ ) for token in doc_en2]

[('I', 'PRON'),
 ('love', 'VERB'),
 ('to', 'PART'),
 ('read', 'VERB'),
 ('interesting', 'ADJ'),
 ('books', 'NOUN'),
 ('in', 'ADP'),
 ('the', 'DET'),
 ('evening', 'NOUN'),
 ('before', 'ADP'),
 ('going', 'VERB'),
 ('to', 'PART'),
 ('sleep', 'VERB'),
 ('.', 'PUNCT')]